-- Products Table
CREATE TABLE IF NOT EXISTS STORE_PRODUCT
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(100)   NOT NULL,
    description        VARCHAR(500)   NOT NULL,
    price              DECIMAL(19, 2) NOT NULL,
    stock_quantity     INT            NOT NULL,
    created_date       TIMESTAMP,
    last_modified_date TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_product_id ON STORE_PRODUCT (id);
